[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/themes/nightfox.toml" ]

[window]
# blur = true
# opacity = 0.9
padding = { x = 4, y = 2 }
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 14
normal = { family = "HackGen35 Console NF", style="Regular" }
bold = { family = "HackGen35 Console NF", style="Bold" }
italic = { family = "HackGen35 Console NF", style="Italic" }
bold_italic = { family = "HackGen35 Console NF", style="Bold Italic" }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
    { key = "¥", chars = "\\"},
    { key = ";", mods = "Command", action = "IncreaseFontSize" },
]

