#!/bin/sh
set -e

NEOVIM_VERSION=stable

CURRENT_DIR=$(
  cd "$(dirname "$0")"
  pwd
)

if [ ! -d "$HOME"/.config ]; then
  mkdir "${HOME}"/.config
fi

ln -vfsn $HOME/dotfiles/nvim $HOME/.config/
ln -vfsnb $HOME/dotfiles/zshrc $HOME/.zshrc
ln -vfsn $HOME/dotfiles/sheldon/ $HOME/.config/
# ln -vfsn $HOME/dotfiles/wezterm/ $HOME/.config/

# install dependencies if in container
if [ -f /.dockerenv ]; then
  sudo apt-get update
  export DEBIAN_FRONTEND=noninteractive

  # For building neovim
  sudo apt-get -y install --no-install-recommends \
    ninja-build \
    gettext \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    cmake \
    g++ \
    pkg-config \
    unzip \
    curl \
    doxygen \
    lua5.3
  # mason.nvim may require
  sudo apt-get -y install --no-install-recommends \
    nodejs \
    npm \
    python3 \
    python3-pip
  # utility
  sudo apt-get -y install --no-install-recommends \
    ripgrep \
    zsh \
	cowsay \
	lolcat

  # Neovim
  mkdir -p /tmp/
  cd /tmp
  git clone https://github.com/neovim/neovim
  cd /tmp/neovim
  git checkout ${NEOVIM_VERSION}
  make -j4 && sudo make install

  # Packer
  git clone --depth 1 https://github.com/wbthomason/packer.nvim\
  ~/.local/share/nvim/site/pack/packer/start/packer.nvim

  # Sheldon
  curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh \
	  | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin

  # cleanup
  sudo rm -rf /var/lib/apt/lists/*
  sudo rm -rf /tmp/*
fi
